
[build]
  base = "./"
  publish = "./output"
  command = "make publish"
  functions = "functions"


[functions]
  included_files = ["admin/**"]
  node_bundler = "esbuild"
  external_node_modules = ["pg-native", "mysql", "oracledb", "tedious", "sqlite3", "pg-query-stream", "better-sqlite3", "mysql2"]

[dev]
  command = "make devserver" # Command to start your dev server
  targetPort = 8000 # The port for your application server, framework or site generator
  port = 8888 # The port that the netlify dev will be accessible on
  publish = "output" # The path to your static content folder
  # jwtSecret = "secret" # The secret used to verify tokens for JWT based redirects
  # jwtRolePath = "app_metadata.authorization.roles" # Object path we should look for role values for JWT based redirects
  autoLaunch = true # a Boolean value that determines if Netlify Dev launches the local server address in your browser
  envFiles = [".env.development.local", ".env.local", ".env.development", ".env"] # The env files to use, ordered by priority (left - highest, right - lowest)
  # to start an https server instead of an http one, configure a certificate and key files
  # [dev.https]
  #   certFile = "cert.pem" # path to the certificate file
  #   keyFile = "key.pem" # path to the private key file