// Asserts invariants about the built site. Requires `npm run build` first.
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readdirSync, readFileSync, existsSync } from 'node:fs';
import path from 'node:path';

const SITE = '_site';

if (!existsSync(SITE)) {
  throw new Error(`${SITE}/ not found — run \`npm run build\` before these tests`);
}

const html = readdirSync(SITE, { recursive: true })
  .map(String)
  .filter((f) => f.endsWith('.html'))
  .map((f) => path.join(SITE, f));

const read = (f) => readFileSync(f, 'utf8');

test('build produced a home page', () => {
  assert.ok(existsSync(path.join(SITE, 'index.html')), 'missing _site/index.html');
});

test('every page has <html lang> and a non-empty <title>', () => {
  const bad = html.flatMap((f) => {
    const s = read(f);
    const errs = [];
    if (!/<html[^>]+lang=/.test(s)) errs.push(`${f}: missing <html lang>`);
    if (!/<title>[^<]+<\/title>/.test(s)) errs.push(`${f}: missing or empty <title>`);
    return errs;
  });
  assert.deepEqual(bad, []);
});

test('every page emits a meta description', () => {
  const bad = html.filter((f) => !/<meta name="description" content="[^"]+"/.test(read(f)));
  assert.deepEqual(bad, []);
});

// Third-party libraries (Bootstrap et al) must be self-hosted from node_modules.
// Our own services are exempt: their widget script has to be served from the same
// origin as the API it talks to, so it can't be vendored into the build.
const FIRST_PARTY_SCRIPT_HOSTS = ['rules-bot.james-nadeau.workers.dev'];

test('front-end JS is self-hosted, not loaded from a third-party CDN', () => {
  const bad = html.flatMap((f) => {
    const remote = [...read(f).matchAll(/<script[^>]+src="(https?:\/\/[^"]+)"/g)].map((m) => m[1]);
    return remote
      .filter((url) => !FIRST_PARTY_SCRIPT_HOSTS.includes(new URL(url).host))
      .map((url) => `${f}: ${url}`);
  });
  assert.deepEqual(bad, []);
});

test('no page renders "Invalid Date" or a bare undefined', () => {
  const bad = html.filter((f) => /Invalid Date|>undefined</.test(read(f)));
  assert.deepEqual(bad, []);
});

test('the stylesheet was compiled and is real CSS, not HTML-wrapped', () => {
  const css = path.join(SITE, 'styles', 'main.css');
  assert.ok(existsSync(css), 'missing _site/styles/main.css');
  assert.ok(!read(css).includes('<html'), 'main.css contains HTML — css.liquid layout not applied');
});

// The Quizzes landing page is generated from the `quizzes` collection, so a new
// quiz file should appear there with no other edit. Guards the data file/tag wiring.
test('the quizzes landing page links every quiz that was built', () => {
  const page = path.join(SITE, 'quizzes', 'index.html');
  assert.ok(existsSync(page), 'missing _site/quizzes/index.html');
  const listed = read(page);
  const built = readdirSync(path.join(SITE, 'quizzes'), { recursive: true })
    .map(String)
    .filter((f) => f.endsWith('index.html') && f !== 'index.html')
    .map((f) => `/quizzes/${path.dirname(f)}/`);
  assert.ok(built.length > 0, 'no quiz pages were built');
  assert.deepEqual(built.filter((url) => !listed.includes(`href="${url}"`)), []);
});

// --- Topics (tags) -----------------------------------------------------
const TOPICS = JSON.parse(readFileSync('content/_data/topics.json', 'utf8'));

// One page per topic is generated by content/tags/topic/topic.pug paginating
// over topics.json, so a new topic should produce a page with no other edit.
test('every topic has a page, and the topic hub links all of them', () => {
  const hub = path.join(SITE, 'tags', 'index.html');
  assert.ok(existsSync(hub), 'missing _site/tags/index.html');
  const listed = read(hub);
  const bad = TOPICS.flatMap((t) => {
    const errs = [];
    if (!existsSync(path.join(SITE, 'tags', t.slug, 'index.html'))) {
      errs.push(`missing _site/tags/${t.slug}/index.html`);
    }
    if (!listed.includes(`href="/tags/${t.slug}/"`)) {
      errs.push(`/tags/ does not link /tags/${t.slug}/`);
    }
    return errs;
  });
  assert.deepEqual(bad, []);
});

// The "Browse by topic" row is the way into the topic pages from the article list.
test('the Information page links every topic that has articles', () => {
  const page = read(path.join(SITE, 'information', 'index.html'));
  const bad = TOPICS.filter((t) => !page.includes(`href="/tags/${t.slug}/"`)).map((t) => t.name);
  assert.deepEqual(bad, []);
});

// A topic page that lists nothing means an article's tag stopped matching.
test('every topic page lists at least one article', () => {
  const bad = TOPICS.filter((t) => {
    const page = read(path.join(SITE, 'tags', t.slug, 'index.html'));
    return !/href="\/information\/[^"]+\/"/.test(page);
  }).map((t) => t.name);
  assert.deepEqual(bad, []);
});

// layouts/article.pug renders each article's topics as links back to their pages.
test('every article page links back to its topics', () => {
  const pages = readdirSync(path.join(SITE, 'information'), { recursive: true })
    .map(String)
    .filter((f) => f.endsWith('index.html') && f !== 'index.html')
    .map((f) => path.join(SITE, 'information', f));
  assert.ok(pages.length > 0, 'no article pages were built');
  const bad = pages.filter((f) => !/href="\/tags\/[a-z0-9-]+\/"/.test(read(f)));
  assert.deepEqual(bad, []);
});

// An unknown tag would render as /tags/undefined/ — a 404 the link checker
// only catches once something links to it.
test('no page links a topic that has no page', () => {
  const slugs = new Set(TOPICS.map((t) => t.slug));
  const bad = html.flatMap((f) =>
    [...read(f).matchAll(/href="\/tags\/([^"/]+)\/"/g)]
      .map((m) => m[1])
      .filter((slug) => !slugs.has(slug))
      .map((slug) => `${f}: /tags/${slug}/`),
  );
  assert.deepEqual(bad, []);
});

// Authoring docs, not pages — and their relative .md links would 404 if published.
test('quiz authoring docs are not published', () => {
  for (const f of ['quizzes/README/index.html', 'quizzes/asked-questions/index.html']) {
    assert.ok(!existsSync(path.join(SITE, f)), `${f} should not be published`);
  }
});

test('kept static assets are copied through', () => {
  for (const f of [
    'images/vermont.svg',
    // The 2022 slide deck is an artefact someone else produced, not a card the
    // build could render from article text, so it stays a committed upload.
    'uploads/7-man-mechanics-2022.pdf',
    'images/7-man-mechanics/coin-toss.jpg',
    'images/7-man-mechanics/keys.jpg',
    'uploads/first-year-officials-quiz-1.docx',
    'uploads/first-year-officials-quiz-2.docx',
    'images/kicking-plays/kickoff-crew-of-5.svg',
    'images/kicking-plays/field-goal-crew-of-4.svg',
    'images/run-pass-plays/every-down-crew-of-5.svg',
    'images/run-pass-plays/goal-line-crew-of-4.svg',
    'images/between-downs/getting-it-back-crew-of-5.svg',
    'images/fouls-enforcement/flag-down-crew-of-4.svg',
    'images/position-cards/referee/run.svg',
    'images/position-cards/umpire/kickoff.svg',
    'images/position-cards/back-judge/field-goal.svg',
    'uploads/nvyfl-5-6-tackle-rules-2026.pdf',
    'uploads/nvyfl-7-8-tackle-rules-2026.pdf',
    'uploads/nvyfl-5-6-tackle-rules-2025.pdf',
    'uploads/nvyfl-7-8-tackle-rules-2025.pdf',
  ]) {
    assert.ok(existsSync(path.join(SITE, f)), `missing _site/${f}`);
  }
});

// The printable cards are build output, not commits — the whole point of the
// pipeline is that they cannot be stale. `uploads/` is what editors put in and
// `cards/` is what the build makes, so the check is not "uploads holds no
// PDFs" — editors upload plenty, and should — but "no card the build renders
// also sits there as a committed copy that could drift from it".
test('no generated card is committed under uploads/', () => {
  const uploaded = new Set(readdirSync('static/uploads').map(String));
  const stale = readdirSync(path.join(SITE, 'cards'))
    .map(String)
    .filter((f) => uploaded.has(f));
  assert.deepEqual(stale, []);
});

// --- Footer / editing link ---------------------------------------------
// The footer is how a non-technical editor finds the CMS at all, so it has to
// be on every page, not just the articles.
test('every page has a footer linking into Pages CMS', () => {
  const bad = html.filter((f) => {
    const footer = read(f).match(/<footer[^>]*>[\s\S]*?<\/footer>/);
    return !footer || !footer[0].includes('href="https://app.pagescms.org/');
  });
  assert.deepEqual(bad, []);
});

// An article whose link doesn't name its own file opens the editor on the
// wrong entry — or on nothing.
test('article and quiz pages deep-link to their own source file', () => {
  const bad = [
    ['information/7-man-mechanics', 'information', 'content/information/7-man-mechanics.md'],
    ['quizzes/quiz-001-expert-mixed', 'quizzes', 'content/quizzes/quiz-001-expert-mixed.md'],
  ].filter(([url, collection, source]) => {
    const want = `/collection/${collection}/edit/${encodeURIComponent(source)}"`;
    return !read(path.join(SITE, url, 'index.html')).includes(want);
  });
  assert.deepEqual(bad.map(([url]) => url), []);
});

// --- Custom domain ------------------------------------------------------
// GitHub Pages reads the custom domain out of the deployed artifact. Without
// this file the domain setting can be dropped on a deploy, and the site falls
// back to the project path — which is what the asset URLs below assume is gone.
test('the build ships a CNAME for the custom domain', () => {
  const cname = path.join(SITE, 'CNAME');
  assert.ok(existsSync(cname), 'missing _site/CNAME');
  assert.equal(read(cname).trim(), 'www.vermont-football-officials.org');
});

// --- /draw: built, and in the navigation --------------------------------
// The drawing page was originally unlisted, reachable only by a direct or
// shared link. It is now in the main nav as "Play Draw", so the check that
// used to assert nothing linked it is inverted: the nav lives in the shared
// layout, so a page that does not carry the link means the layout broke.
// It stays out of the article collections either way — it is a tool, not an
// article, and `eleventyExcludeFromCollections` in content/draw/index.pug is
// what keeps it out of them.
test('the build wrote /draw', () => {
  assert.ok(existsSync(path.join(SITE, 'draw', 'index.html')), 'missing _site/draw/index.html');
});

test('every page links /draw from the main navigation', () => {
  const bad = html.filter((f) => {
    const nav = read(f).match(/<nav [^>]*id="header"[^>]*>[\s\S]*?<\/nav>/);
    return !nav || !/href="\/draw\/"/.test(nav[0]);
  });
  assert.deepEqual(bad, [], '/draw is linked from the nav in layouts/main.pug');
});

// A stray topic tag on content/draw/index.pug would slip it into a topic page
// regardless of eleventyExcludeFromCollections, which only keeps Eleventy's own
// collections clean — the Information index and every topic page are exactly
// where that would surface. The nav now names /draw on every page, so this
// looks only at the article listing itself, not the whole document.
test('/draw appears in no collection listing', () => {
  const listings = [
    path.join(SITE, 'information', 'index.html'),
    ...TOPICS.map((t) => path.join(SITE, 'tags', t.slug, 'index.html')),
  ];
  const bad = listings.filter((f) => {
    const main = read(f).match(/<main [^>]*id="content"[^>]*>[\s\S]*?<\/main>/);
    return !main || main[0].includes('/draw');
  });
  assert.deepEqual(bad, []);
});

// The site is served from the domain root, so a build that stamped a path
// prefix onto the CSS and JS URLs would 404 both and leave the page unstyled.
test('asset URLs are root-relative, with no project path prefix', () => {
  const bad = html.filter((f) => {
    const s = read(f);
    return (
      !s.includes('href="/styles/main.css"') ||
      !s.includes('src="/js/bootstrap.bundle.min.js"') ||
      // A prefixed build stamps <base> and rewrites every local URL; the CMS
      // links to github.com/jamesjnadeau/vermont-football-officials, so only
      // root-relative occurrences count.
      /(?:href|src)="\/vermont-football-officials\//.test(s)
    );
  });
  assert.deepEqual(bad, []);
});
