backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow

    
media_folder: "content/uploads" # Media files will be stored in the repo under static/images/uploads
public_folder: "/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections: # A list of collections the CMS should be able to edit
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Information" # Used in the UI, ie.: "New Post"
    folder: "content/information" # The path to the folder where the documents are stored
    format: frontmatter
    sort: "date:desc" # Default is title:asc
    create: true # Allow users to create new documents in this collection
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string", tagname: "h1", class: "entry-title"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      # - {label: "Category", name: "category", widget: "string", default: "Information"}
  - name: "pages"
    label: "Pages"
    folder: "content/pages"  
    format: frontmatter
    create: true # Allow users to create new documents in this collection
    fields:
      - {label: "Page Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}