#!/usr/bin/env node
// Writes static/cms/site/vendor.js: the vendored ContentTools internals the
// site's editor additions need, re-exported under their real names.
//
// The build exports them from content-hashed chunks under one-letter aliases
// (`ContentTools as C`), and both the file names and the letters change with
// every build. ES modules are singletons by URL, so importing the same chunk
// file edit.js imports gives the site code the very objects the editor runs
// on — which is the whole trick. This file keeps that import honest: it is
// regenerated by vendor.sh, and it throws, naming the export, when a build
// no longer has something the site code needs.
//
//     node tools/content-tools/link-site.mjs           # write vendor.js
//     node tools/content-tools/link-site.mjs --check   # exit 1 if stale
import { readFileSync, readdirSync, writeFileSync, mkdirSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = fileURLToPath(new URL('../../', import.meta.url));
export const OUT = path.join(ROOT, 'static/cms/site/vendor.js');

// `local` names as written in the ContentTools source, and what to call them.
// The editor hands `setup` the library itself (window.contentToolsEdit); what
// it doesn't hand over is how markdown becomes the region's HTML and back,
// which the site extends for its grids and card notes. The last five are
// only for the tests, which build an editor without edit.js.
const WANTED = {
  LIBRARY: 'LIBRARY',
  MarkdownDocument: 'MarkdownDocument',
  blockToHTML: 'blockToHTML',
  MARKDOWN_PROFILE: 'MARKDOWN_PROFILE',
  allowTools: 'allowTools',
  filterToolGroups: 'filterToolGroups',
  ContentToolsEditor: 'ContentToolsEditor',
  TAG_NAME: 'EDITOR_TAG',
};
export const NAMES = Object.values(WANTED);

export function exportsOf(src) {
  const block = src.match(/export\s*\{([^}]*)\}\s*;?\s*$/);
  if (!block) return [];
  return block[1].split(',').map((s) => s.trim()).filter(Boolean).map((s) => {
    const [local, alias] = s.split(/\s+as\s+/);
    return { local, alias: alias ?? local };
  });
}

export function render(chunksDir) {
  const found = new Map();
  for (const file of readdirSync(chunksDir).filter((f) => f.endsWith('.js')).sort()) {
    for (const { local, alias } of exportsOf(readFileSync(path.join(chunksDir, file), 'utf8'))) {
      if (!(local in WANTED)) continue;
      if (found.has(local)) throw new Error(`${local} is exported by both ${found.get(local).file} and ${file}`);
      found.set(local, { file, alias });
    }
  }
  const missing = Object.keys(WANTED).filter((local) => !found.has(local));
  if (missing.length) {
    throw new Error(`the vendored ContentTools no longer exports ${missing.join(', ')} — static/cms/site/ needs updating for this build`);
  }
  const byFile = new Map();
  for (const [local, { file, alias }] of found) {
    byFile.set(file, [...(byFile.get(file) ?? []), `${alias} as ${WANTED[local]}`]);
  }
  const lines = [...byFile].map(([file, names]) => `export { ${names.join(', ')} } from '../chunks/${file}';`);
  return `// Generated by tools/content-tools/link-site.mjs from static/cms/chunks/ — do not edit.\n${lines.join('\n')}\n`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const next = render(path.join(ROOT, 'static/cms/chunks'));
  if (process.argv.includes('--check')) {
    let current = '';
    try { current = readFileSync(OUT, 'utf8'); } catch {}
    if (current !== next) {
      console.error('static/cms/site/vendor.js is stale — run node tools/content-tools/link-site.mjs');
      process.exit(1);
    }
  } else {
    mkdirSync(path.dirname(OUT), { recursive: true });
    writeFileSync(OUT, next);
  }
}
