#!/usr/bin/env node
// Writes static/cms/site/signals.js: every official signal — drawing, alt
// text and caption — for the editor's signal grid dialog.
//
// The list is taken from the one grid on all-signals-listed-and-diagrammed.md
// that shows all of them with captions, so the dialog's wording is the site's
// wording, and there is one place to fix a caption.
//
//     node tools/content-tools/signals.mjs           # write signals.js
//     node tools/content-tools/signals.mjs --check   # exit 1 if stale
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { findGrids, parseGrid } from '../../static/cms/site/grids.js';

const ROOT = fileURLToPath(new URL('../../', import.meta.url));
const SOURCE = path.join(ROOT, 'content/information/all-signals-listed-and-diagrammed.md');
export const OUT = path.join(ROOT, 'static/cms/site/signals.js');

export function render() {
  const grids = findGrids(readFileSync(SOURCE, 'utf8')).map(parseGrid);
  const all = grids.find((g) => g?.kind === 'signal-grid' && g.captioned);
  if (!all) throw new Error(`${SOURCE} has no captioned signal grid`);
  const items = all.items.map(({ src, alt, caption }) => ({ src, alt, caption }));
  return `// Generated by tools/content-tools/signals.mjs from content/information/all-signals-listed-and-diagrammed.md — do not edit.\nexport const SIGNALS = ${JSON.stringify(items, null, 2)};\n`;
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const next = render();
  if (process.argv.includes('--check')) {
    let current = '';
    try { current = readFileSync(OUT, 'utf8'); } catch {}
    if (current !== next) {
      console.error('static/cms/site/signals.js is stale — run node tools/content-tools/signals.mjs');
      process.exit(1);
    }
  } else {
    writeFileSync(OUT, next);
  }
}
